name: Build Docs

on:
  workflow_run:
    workflows: ["Build Matrix"]
    branches: [main]
    types: 
      - completed

env:
  DOXYGEN_VERSION: 1.9.6

jobs:
  build:
    name: build docs
    runs-on: ubuntu-latest
    steps:
    - name: s1
      run: |
        echo "Building docs"