name: Code Coverage

on:
  workflow_run:
    workflows: ["Test Matrix"]
    branches: [main]
    types: 
      - completed

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: coverage
      steps:
        - name: setting up
          run:
            echo "Checking coverage ..."