name: cppcheck-action
on:
  workflow_run:
    workflows: ["Build Matrix"]
    branches: [main]
    types: 
      - completed

jobs:
  check:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        run: |
          echo "Analyzing sources ..."