name: Test Matrix

on:
  workflow_run:
    workflows: ["Build Matrix"]
    branches: [main]
    types: 
      - completed
jobs:
  test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC", artifact: "Windows-MSVC.7z",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
        # Test Build fails with MinGW
        # - {
        #     name: "Windows Latest MinGW", artifact: "Windows-MinGW.7z",
        #     os: windows-latest,
        #     cc: "gcc", cxx: "g++"
        #   }
        - {
            name: "Ubuntu Latest GCC", artifact: "Linux.7z",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++"
          }
        - {
            name: "macOS Latest Clang", artifact: "macOS.7z",
            os: macos-latest,
            cc: "clang", cxx: "clang++"
          }
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo "Testing"